last commit

diff --git a/.pipelines/templates/release.yml b/.pipelines/templates/release.yml
--- a/.pipelines/templates/release.yml
+++ b/.pipelines/templates/release.yml
@@ -1,16 +1,17 @@
 jobs:
-- job: 'Version'
-  displayName: 'Get version'
+- job: version
+  displayName: 'Get the version number'
   steps:
     - bash: |
+        set -eux  # exit on error
         ver=$(cat VERSION)
         echo $ver
         echo "##vso[task.setvariable variable=version;isOutput=true]$ver"
       displayName: Set Version
       name: setVer
-- job: GitHubRelease
+- job: githubRelease
   displayName: GitHub Release
-  dependsOn: Version
+  dependsOn: version
   variables:
     version: $[ dependencies.Version.outputs['setVer.version'] ]
   steps:
